name: Daily crawl of JavRate actor data

on:
  schedule:
    - cron: '0 0 */5 * *'
  workflow_dispatch:

jobs:
  crawl-and-save:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.10 environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Configure Git user information
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions-crawler@github.com"

      - name: Run crawler script
        run: python Widgets/javrate_actor_crawler.py

      - name: Check if data file exists
        id: check_file
        run: |
          if [ -f "Widgets/javrate_actors.json" ]; then
            echo "file_exists=true" >> $GITHUB_OUTPUT
          else
            echo "file_exists=false" >> $GITHUB_OUTPUT
            exit 1
          fi

      - name: Commit and push data file
        if: steps.check_file.outputs.file_exists == 'true'
        run: |
          git add Widgets/javrate_actors.json
          git commit -m "Auto-update: JavRate actor data"
          git push
          echo "Data file successfully committed to repository"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
